language: node_js
node_js:
  - "0.12"
  - "0.11"
  - "0.10"
  - "0.8"
  - "0.6"
  - "iojs"
  - "iojs-v1.0.4"

env:
  - REDIS_URL=tcp://localhost:6379

services:
  - redis-server

email:
    on_success: never
